---
name: "Start SSH server"
description: "Start SSH server"
author: "Rafael Alexandre"

inputs:
  ssh_private_key_path:
    description: "SSH private key path (relative to the project root)"
    required: true
  ssh_public_key_path:
    description: "SSH public key path (relative to the project root)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install OpenSSH.
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
      shell: bash

    - name: Start SSH server.
      run: |
        sudo service ssh start
        sudo ssh-keygen -A
      shell: bash

    - name: Add SSH keys.
      run: |
        mkdir -p ~/.ssh
        cat "${{ inputs.ssh_private_key_path }}" > ~/.ssh/id_rsa
        cat "${{ inputs.ssh_public_key_path }}" > ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/id_rsa ~/.ssh/authorized_keys
      shell: bash

    - name: Test SSH connection.
      run: |
        # 'runner' is the default github actions user in ubuntu.
        ssh -o StrictHostKeyChecking=no runner@localhost -i ~/.ssh/id_rsa "echo 'SSH works!'"
      shell: bash
