---
name: "Release docker image"
description: "Release docker imagever"
author: "Rafael Alexandre"

inputs:
  docker_image_name:
    description: "Name given to the docker image"
    required: true
  docker_username:
    description: "Username to login to Docker Hub"
    required: true
  docker_password:
    description: "Password to login to Docker Hub"
    required: true
  dockerfile_context:
    description: "Path where the dockerfile being built is located"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker mimage image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.dockerfile_context }}
        push: true
        tags: |
          ${{ inputs.docker_username }}/${{ inputs.docker_image_name }}:latest
          ${{ inputs.docker_username }}/${{ inputs.docker_image_name }}:${{ github.sha }}
