---
name: Playbook-test

'on':
  workflow_call:
    inputs:
      playbook_path:
        description: "Playbook path (relative to the project root)"
        required: true
        type: string

jobs:

  playbook-test:
    name: Playbook-test

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install ansible

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/inventory ./inventory
          ansible-galaxy install -r requirements.yml

      - name: Test the playbook's syntax.
        run: |
          ansible-playbook ${{ inputs.playbook_path }} --syntax-check

      - name: Test the playbook.
        run: ansible-playbook ${{ inputs.playbook_path }}
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook ${{ inputs.playbook_path }} | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
          rm -rf ${idempotence}
        env:
          ANSIBLE_FORCE_COLOR: '1'
